config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  root 'employees#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :employees
  resources :rest, :only => [] do
    collection do
      post 'login'
      get 'get_all'
      get 'get_emp'
      post 'add_emp'
      post 'update_emp'
      get 'delete_emp'
      post 'set_password'
    end
  end
end

app/models/employee.rb
require('employee_status')

class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  has_many :employee_to_roles
  has_many :employee_roles, :through => :employee_to_roles
  validates :username, presence: true
  validates :bStatus, presence: true
  validates :firstName, presence: true
  validates :lastName, presence: true
  validates :dateOfBirth, presence: true

  def as_json(options)
    return {
        id: id,
        bStatus: (bStatus == EmployeeStatus::ACTIVE ? 'ACTIVE' : 'INACTIVE'),
        username: username,
        firstName: firstName,
        middleInitial: middleInitial,
        lastName: lastName,
        dateOfBirth: dateOfBirth.to_date,
        dateOfEmployment: (dateOfEmployment.nil? ? nil : dateOfEmployment.to_date),
        email: email
    }
  end

  def hasEmploymentDate
    !dateOfEmployment.to_s.empty?
  end

#  def hasEmploymentDate=(hed)
#    if hed == false || hed == 0
#      dateOfBirth = nil
#    else
#      if dateOfBirth.to_s.empty?
#        dateOfBirth = Date.now
#      end
#    end
#  end

  def can? do_what
    case do_what
      when :add
        employee_roles.pluck(:role).include?('ROLE_ADD_EMP')
      when :delete
        employee_roles.pluck(:role).include?('ROLE_DELETE_EMP')
      when :update
        employee_roles.pluck(:role).include?('ROLE_UPDATE_EMP')
      when :set_password
        employee_roles.pluck(:role).include?('ROLE_SET_PASSWORD')
      else
        false
    end
  end

  def will_save_change_to_email?
    false
  end

  def self.default_scope
    where(:bStatus => EmployeeStatus::ACTIVE)
  end
end

app/controllers/employees_controller.rb
require('employee_status')

class EmployeesController < ApplicationController
  before_action :authenticate_employee!
  protect_from_forgery with: :exception

  def index;
    @employees = Employee.all
  end

  def create
    if !current_employee.try(:can?, :add)
      @messages = 'Not authorized to add an employee'
      @employees = index
      render :index
      return
    end

    @employee = Employee.new(employee_params)
    @employee.bStatus = EmployeeStatus::ACTIVE

    if !current_employee.try(:can?, :set_password)
      @employee.password = SecureRandom.hex
    else
      @employee.employee_roles = EmployeeRole.where(:role => params[:newroles])
    end

    begin
      if @employee.save
        redirect_to @employee
        return
      else
        @messages = @employee.errors.full_messages
        render :new
      end
    rescue ActiveRecord::StatementInvalid => e
      @messages = e.message
      render :new
    end
  end

  def new
    if !current_employee.try(:can?, :add)
      @messages = 'Not authorized to add an employee'
      @employees = index
      render :index
      return
    end
    @employee = Employee.new
  end

  def show;
    begin
      @employee = Employee.select(returned_employee_fields).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @messages = 'Invalid employee id'
      @employees = index
      render :index
    end
  end

  def edit;
    if !current_employee.try(:can?, :update)
      @messages = 'Not authorized to update an employee'
      @employees = index
      render :index
      return
    end

    begin
      @employee = Employee.select(returned_employee_fields).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @messages = 'Invalid employee id'
      @employees = index
      render :index
    end
  end

  def update;
    if !current_employee.try(:can?, :update)
      @messages = 'Not authorized to update an employee'
      @employees = index
      render :index
      return
    end

    if params[:employee][:hasEmploymentDate].to_i == 0
      params[:employee][:dateOfEmployment] = nil
    else
      params[:employee][:dateOfEmployment] = params[:employee]['dateOfEmployment(1i)'] + '-' + params[:employee]['dateOfEmployment(2i)'] + '-' + params[:employee]['dateOfEmployment(3i)']
    end
    params[:employee][:dateOfBirth] = params[:employee]['dateOfBirth(1i)'] + '-' + params[:employee]['dateOfBirth(2i)'] + '-' + params[:employee]['dateOfBirth(3i)']
    params[:employee].delete(:hasEmploymentDate)
    params[:employee].delete('dateOfBirth(1i)')
    params[:employee].delete('dateOfBirth(2i)')
    params[:employee].delete('dateOfBirth(3i)')
    params[:employee].delete('dateOfEmployment(1i)')
    params[:employee].delete('dateOfEmployment(2i)')
    params[:employee].delete('dateOfEmployment(3i)')

    p_employee = Employee.new(employee_params)

    begin
      @employee = Employee.select(returned_employee_fields).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @messages = 'Unable to find employee record'
      render :index
      return
    end

    @employee.username = p_employee.username
    @employee.email = p_employee.email
    @employee.firstName = p_employee.firstName
    @employee.middleInitial = p_employee.middleInitial
    @employee.lastName = p_employee.lastName
    @employee.dateOfBirth = p_employee.dateOfBirth
    @employee.dateOfEmployment = p_employee.dateOfEmployment
    @employee.bStatus = p_employee.bStatus
    if current_employee.try(:can?, :set_password)
      if !p_employee.password.to_s.empty?
        @employee.password = p_employee.password
      end
      @employee.employee_roles = EmployeeRole.where(:role => params[:newroles])
    end
    if @employee.save
      render :show
    else
      @messages = @employee.errors.full_messages
      render :edit
    end
  end

  def destroy
    if !current_employee.try(:can?, :delete)
      @messages = 'Not authorized to delete an employee'
      @employees = index
      render :index
      return
    end

    begin
      employee = Employee.select(returned_employee_fields).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @messages = 'Employee record not found'
      render :index
      return
    end

    employee.bStatus = EmployeeStatus::INACTIVE
    if employee.save
      @employees = index
      render :index
    else
      @messages = @employee.errors.full_messages
      render :edit
    end

  end

  protected

  def employee_params
    if current_employee.try(:can?, :set_password)
      params.require(:employee).permit(:id, :username,
                                       :firstName, :middleInitial, :lastName,
                                       :dateOfBirth,
                                       :dateOfEmployment,
                                       :bStatus, :email, :password, :employee_roles)
    else
      params.require(:employee).permit(:id, :username,
                                       :firstName, :middleInitial, :lastName,
                                       :dateOfBirth,
                                       :dateOfEmployment,
                                       :bStatus, :email)
    end
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<h1>Employee#edit</h1>
<div id='test_automation' name='Employee#edit'/>
<%= form_for @employee do |f| %>
    <table>
      <tr>
        <td><%= f.label :username, 'Username' %></td>
        <td><%= f.text_field :username %></td>
      </tr>
      <tr>
        <td><%= f.label :email, 'Email' %></td>
        <td><%= f.text_field :email %></td>
      </tr>
      <tr>
        <td><%= f.label :firstName, 'First name' %></td>
        <td><%= f.text_field :firstName %></td>
      </tr>
      <tr>
        <td><%= f.label :middleInitial, 'M' %></td>
        <td><%= f.text_field :middleInitial %></td>
      </tr>
      <tr>
        <td><%= f.label :lastName, 'Last name' %></td>
        <td><%= f.text_field :lastName %></td>
      </tr>
      <tr>
        <td><%= f.label :dateOfBirth, 'Date of birth' %></td>
        <td><%= f.date_select :dateOfBirth, start_year: Date.today.prev_year(100).year, end_year: Date.today.year %></td>
      </tr>
      <tr>
        <td><%= f.label :dateOfEmployment, 'Date of employment' %></td>
        <td><table><tr><td><%= f.check_box :hasEmploymentDate %></td><td><%= f.date_select :dateOfEmployment, start_year: Date.today.prev_year(100).year, end_year: Date.today.year %></td></tr></table></td>
      </tr>
      <% if @employee.has_attribute? :encrypted_password %>
        <tr>
          <td><%= f.label :password, 'Password' %></td>
          <td><%= f.password_field :password %></td>
        </tr>
          <tr>
            <td><%= f.label :roles, 'Roles'%></td>
            <td>
              <%= select_tag(
                      :newroles,
                        options_for_select(EmployeeRole.pluck(:role), @employee.employee_roles.pluck(:role)),
                        { :disabled => true, :multiple => true, :size => 5, :id => "employee_role" })
              %>
            </td>
          </tr>
      <% end %>
      <tr><td><%= f.submit %></td><td><%= link_to 'Delete', employee_path(@employee), method: :delete %></td></tr>
    </table>
    <%= @messages %>
    <%= f.hidden_field :bStatus, :value => 0 %>
<% end %>

app/views/employees/index.html.erb
<h1>Employee#index</h1>
<div id='test_automation' name='Employee#index'/>

<table>
  <tr>
    <th>username</th>
    <th>Email</th>
    <th>First name</th>
    <th>MI</th>
    <th>Last name</th>
    <th>Date of birth</th>
    <th>Date of employment</th>
  </tr>
  <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.username%></td>
        <td><%= employee.email%></td>
        <td><%= employee.firstName%></td>
        <td><%= employee.middleInitial%></td>
        <td><%= employee.lastName%></td>
        <td><%= employee.dateOfBirth%></td>
        <td><%= employee.dateOfEmployment%></td>
        <% if current_employee.can? :update %>
          <td><%= button_to 'Edit', edit_employee_path(employee), method: :get %></td>
        <% elsif current_employee.can? :delete %>
          <td><%= button_to 'Delete', employee_path(employee), method: :delete %></td>
        <% end %>
      </tr>
  <% end %>
</table>
<p><%= @messages %></p>

app/views/employees/new.html.erb
<h1>Employee#new</h1>
<div id='test_automation' name='Employee#new'/>
<%= form_for @employee do |f| %>
    <table>
      <tr><td><%= f.label :username, 'Username' %></td><td><%= f.text_field :username %></td></tr>
      <tr><td><%= f.label :email, 'Email' %></td><td><%= f.email_field :email %></td></tr>
      <% if current_employee.try :can?, :set_password %>
        <tr><td><%= f.label :password, 'Password' %></td><td><%= f.password_field :password %></td></tr>
      <% end %>
      <tr><td><%= f.label :firstName, 'First name' %></td><td><%= f.text_field :firstName %></td></tr>
      <tr><td><%= f.label :middleInitial, 'M' %></td><td><%= f.text_field :middleInitial %></td></tr>
      <tr><td><%= f.label :lastName, 'Last name' %></td><td><%= f.text_field :lastName %></td></tr>
      <tr><td><%= f.label :dateOfBirth, 'Date of birth' %></td><td><%= f.text_field :dateOfBirth %></td></tr>
      <tr><td><%= f.label :dateOfEmployment, 'Date of employment' %></td><td><%= f.text_field :dateOfEmployment %></td></tr>
      <% if current_employee.try :can?, :set_password %>
          <tr>
            <td><%= f.label :roles, 'Roles'%></td>
            <td>
              <%= select_tag(
                      :newroles,
                        options_for_select(EmployeeRole.pluck(:role), @employee.employee_roles.pluck(:role)),
                        { :multiple => true, :size => 5, :id => "employee_role" })
              %>
            </td>
          </tr>
      <% end %>
      <tr><td><%= f.submit %></td></tr>
      <tr><td colspan="2"><%= @messages %></td></tr>
    </table>
<% end %>

app/views/employees/show.html.erb
<h1>Employee#show</h1>
<div id='test_automation' name='Employee#show'/>
<table>
  <tr><td>username</td><td><%= @employee.username%></td></tr>
  <tr><td>First name</td><td><%= @employee.firstName%></td></tr>
  <tr><td>Middle Initial</td><td><%= @employee.middleInitial%></td></tr>
  <tr><td>Last Name</td><td><%= @employee.lastName%></td></tr>
  <tr><td>Date of Birth</td><td><%= @employee.dateOfBirth%></td></tr>
  <tr><td>Date of Employment</td><td><%= @employee.dateOfEmployment%></td></tr>
  <tr><td>Roles</td><td>
    <%= select_tag(
            :unused,
            options_for_select(@employee.employee_roles.pluck(:role), @employee.employee_roles.pluck(:role)),
            { :multiple => true, :id => "employee_role" })
    %>
  </td></tr>
</table>